import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { dehydrate, QueryClient } from "@tanstack/react-query";
import {
  getAllDataPrefetchQuery,
  useGetAllDataQuery,
} from "@/restAPI/data/getAllData";
import { MenuBar } from "@/features/layout/menuBars/MenuBar";
import { HomeMenuBarNavigation } from "@/features/layout/menuBars/homePage/HomeMenuBarNavigation";
import { ChartCard } from "@/features/charts/ChartCard";
import { HomepageCovidIncidenceCharts } from "@/features/charts/homepage/HomepageCovidIncidenceCharts";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data, error, isFetching } = useGetAllDataQuery(true);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MenuBar
        navigationComponent={<HomeMenuBarNavigation />}
        pageTitle={"Page Title"}
      />
      <HomepageCovidIncidenceCharts />
    </>
  );
}

export const getServerSideProps = async () => {
  const queryClient = new QueryClient();
  await getAllDataPrefetchQuery(queryClient);
  return { props: { dehydratedState: dehydrate(queryClient) } };
};
