import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { dehydrate, QueryClient } from "@tanstack/react-query";
import {
  getAllDataPrefetchQuery,
  useGetAllDataQuery,
} from "@/restAPI/data/getAllData";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data, error, isFetching } = useGetAllDataQuery(true);
  console.log(data, isFetching);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <pre>{JSON.stringify(data, null, 2)}</pre>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const queryClient = new QueryClient();
  await getAllDataPrefetchQuery(queryClient);
  return { props: { dehydratedState: dehydrate(queryClient) } };
};
